### ISSUE TITLE
Should create needed device file on first invocation for example using udev

### ISSUE THREAD

**Issue by petterreinholdtsen** [namiltd/megactl#4]
At the moment, neither megactl nor megasasctl create the device file they need when they run for the first time.  It would
provide a better user experience if the device files were created automatically.  It could either be done using a udev rule,
or by doing mknod inside the program on first invocation, similar to how megacli do it.

The files /dev/megadev0 and /dev/megaraid_sas_ioctl_node could be created using something similar to this:

```
sudo mknod /dev/megaraid_sas_ioctl_node c $(awk '/megaraid_sas_ioctl/ {print $1}' /proc/devices) 0
```

**Comment by namiltd** [comment]
Done: https://github.com/namiltd/megactl/commit/b02b26538e1fe9281d6a3d5b449de8ce59b2f220

**Comment by petterreinholdtsen** [comment]
Very good.  Thank you!  I hope it make it into a new release soon.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by namiltd** [comment]
The code has been rebuilt, please check it again.

**Comment by petterreinholdtsen** [comment]
[Mieczyslaw Nalewaj]
> The code has been rebuilt, please check it again.

Seem to work fine.  Thank you for the implementation.  I was looking at
making a udev rule to create it during kernel module load, but did not
manage to finish it before your solution was implemented. :)

-- 
Happy hacking
Petter Reinholdtsen
