### ISSUE TITLE
Provide man pages for the megactl and megasasctl?

### ISSUE THREAD

**Issue by petterreinholdtsen** [namiltd/megactl#5]
Every program in Debian is expected to have manual pages explaining how to run the program. Would it be possible to provide such manual pages in the source for the installed binaries megactl and megasasctl? The man pages could be created based on the -h output, perhaps even automatically generated from such output.

**Comment by namiltd** [comment]
All these commands have the -h option. All that remains is to look for a converter to the man format.

**Comment by petterreinholdtsen** [comment]
[Mieczyslaw Nalewaj]
> All commands have the -h option. All that remains is to look for a
> converter to the man format.

One option is txt2man.  There is also rst2man for more manual
maintenance.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by namiltd** [comment]
Done: https://github.com/namiltd/megactl/commit/5f0817181a862c35ef1e358a33e61fa2345c3b7b
